In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import seaborn as sns

In [2]:
from vaccination_functions import *

In [3]:
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.feature_selection import f_regression

In [4]:
tx_mmr_vac_rates = pd.read_csv("../TX_MMR_vax_rate_24_25.csv")
counties_with_vac = tx_mmr_vac_rates['County'].unique()

In [ ]:
acs_data_path = "../acs_data/"

In [ ]:
age_df = pd.read_csv(acs_data_path+"tx_county_agePop_24.csv")
age_var_df = pd.read_csv(acs_data_path+"ageVars_acs.csv")

race_df = pd.read_csv(acs_data_path+"x_county_racePop_24.csv")
race_var_df = pd.read_csv(acs_data_path+"raceVars_acs.csv")

education_df = pd.read_csv(acs_data_path+"tx_county_education_24.csv")
education_var_df = pd.read_csv(acs_data_path+"educationVars_acs.csv")

enrollment_df = pd.read_csv(acs_data_path+"tx_county_enrollment_24.csv")
enrollment_var_df = pd.read_csv(acs_data_path+"enrollmentVars_acs.csv")

poverty_df = pd.read_csv(acs_data_path+"tx_county_poverty_24.csv")
poverty_var_df = pd.read_csv(acs_data_path+"povertyVars_acs.csv")

In [6]:
age_with_var_all, age_with_var_no_gender = create_predictor_datasets(age_df, age_var_df, counties_with_vac)
race_with_var_all, race_with_var_no_gender = create_predictor_datasets(race_df, race_var_df, counties_with_vac)
education_with_var_all, education_with_var_no_gender = create_predictor_datasets(education_df, education_var_df, counties_with_vac)
enrollment_with_var_all, enrollment_with_var_no_gender = create_predictor_datasets(enrollment_df, enrollment_var_df, counties_with_vac)
poverty_with_var_all, poverty_with_var_no_gender = create_predictor_datasets(poverty_df, poverty_var_df, counties_with_vac)

In [7]:
age_with_var_no_gender['Estimate_Total_Under_5'] = age_with_var_all['Estimate_Total_Male_Under_5'] + age_with_var_all['Estimate_Total_Female_Under_5']
age_with_var_no_gender['Estimate_Total_5_9'] = age_with_var_all['Estimate_Total_Male_5_9'] + age_with_var_all['Estimate_Total_Female_5_9']
age_with_var_no_gender['Estimate_Total_10_14'] = age_with_var_all['Estimate_Total_Male_10_14'] + age_with_var_all['Estimate_Total_Female_10_14']
age_with_var_no_gender['Estimate_Total_15_17'] = age_with_var_all['Estimate_Total_Male_15_17'] + age_with_var_all['Estimate_Total_Female_15_17']
age_with_var_no_gender['Estimate_Total_18_19'] = age_with_var_all['Estimate_Total_Male_18_and_19'] + age_with_var_all['Estimate_Total_Female_18_and_19']
age_with_var_no_gender['Estimate_Total_21'] = age_with_var_all['Estimate_Total_Male_21'] + age_with_var_all['Estimate_Total_Female_21']
age_with_var_no_gender['Estimate_Total_22_24'] = age_with_var_all['Estimate_Total_Male_22_24'] + age_with_var_all['Estimate_Total_Female_22_24']
age_with_var_no_gender['Estimate_Total_25_29'] = age_with_var_all['Estimate_Total_Male_25_29'] + age_with_var_all['Estimate_Total_Female_25_29']
age_with_var_no_gender['Estimate_Total_30_34'] = age_with_var_all['Estimate_Total_Male_30_34'] + age_with_var_all['Estimate_Total_Female_30_34']
age_with_var_no_gender['Estimate_Total_35_39'] = age_with_var_all['Estimate_Total_Male_35_39'] + age_with_var_all['Estimate_Total_Female_35_39']


In [8]:
age_with_var_no_gender['Estimate_Total_40_44'] = age_with_var_all['Estimate_Total_Male_40_44'] + age_with_var_all['Estimate_Total_Female_40_44']
age_with_var_no_gender['Estimate_Total_45_49'] = age_with_var_all['Estimate_Total_Male_45_49'] + age_with_var_all['Estimate_Total_Female_45_49']
age_with_var_no_gender['Estimate_Total_50_54'] = age_with_var_all['Estimate_Total_Male_50_54'] + age_with_var_all['Estimate_Total_Female_50_54']
age_with_var_no_gender['Estimate_Total_55_59'] = age_with_var_all['Estimate_Total_Male_55_59'] + age_with_var_all['Estimate_Total_Female_55_59']
age_with_var_no_gender['Estimate_Total_60_61'] = age_with_var_all['Estimate_Total_Male_60_and_61'] + age_with_var_all['Estimate_Total_Female_60_and_61']
age_with_var_no_gender['Estimate_Total_62_64'] = age_with_var_all['Estimate_Total_Male_62_64'] + age_with_var_all['Estimate_Total_Female_62_64']
age_with_var_no_gender['Estimate_Total_65_66'] = age_with_var_all['Estimate_Total_Male_65_and_66'] + age_with_var_all['Estimate_Total_Female_65_and_66']
age_with_var_no_gender['Estimate_Total_67_69'] = age_with_var_all['Estimate_Total_Male_67_69'] + age_with_var_all['Estimate_Total_Female_67_69']
age_with_var_no_gender['Estimate_Total_70_74'] = age_with_var_all['Estimate_Total_Male_70_74'] + age_with_var_all['Estimate_Total_Female_70_74']
age_with_var_no_gender['Estimate_Total_75_79'] = age_with_var_all['Estimate_Total_Male_75_79'] + age_with_var_all['Estimate_Total_Female_75_79']
age_with_var_no_gender['Estimate_Total_80_84'] = age_with_var_all['Estimate_Total_Male_80_84'] + age_with_var_all['Estimate_Total_Female_80_84']
age_with_var_no_gender['Estimate_Total_85_over'] = age_with_var_all['Estimate_Total_Male_85_and_over'] + age_with_var_all['Estimate_Total_Female_85_and_over']

In [9]:
age_with_var_all_percent, age_with_var_no_gender_percent = create_predictor_percentages(age_with_var_all, age_with_var_no_gender)
race_with_var_all_percent, race_with_var_no_gender_percent = create_predictor_percentages(race_with_var_all, race_with_var_no_gender)
education_with_var_all_percent, education_with_var_no_gender_percent = create_predictor_percentages(education_with_var_all, education_with_var_no_gender)
enrollment_with_var_all_percent, enrollment_with_var_no_gender_percent = create_predictor_percentages(enrollment_with_var_all, enrollment_with_var_no_gender)

In [10]:
### Predictor datasets with vaccination rates for percentages
race_vac_set_all_percent, race_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, race_with_var_all_percent, race_with_var_no_gender_percent)
age_vac_set_all, age_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, age_with_var_all_percent, age_with_var_no_gender_percent)
education_vac_set_all_percent, education_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, education_with_var_all_percent, education_with_var_no_gender_percent)
enrollment_vac_set_all_percent, enrollment_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, enrollment_with_var_all_percent, enrollment_with_var_no_gender_percent)

c:\Users\19037\Documents\Measels_Vaccination\code_backup\vaccination_functions.py:93: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  single_pred_df_all = pd.merge(predictor_df_all, vac_df_rel, on=['County'])


In [11]:
all_acs_variables_percent = combine_all_acs_variables(education_with_var_all_percent, race_with_var_all_percent, enrollment_with_var_all_percent, age_with_var_all_percent, poverty_with_var_all, percent=True, gender=True)
all_acs_variables_no_gender_percent = combine_all_acs_variables(education_with_var_no_gender_percent, race_with_var_no_gender_percent, enrollment_with_var_no_gender_percent, age_with_var_no_gender_percent, poverty_with_var_all, percent=True)
all_vac_set_percent, all_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, all_acs_variables_percent, all_acs_variables_no_gender_percent)

c:\Users\19037\Documents\Measels_Vaccination\code_backup\vaccination_functions.py:105: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  edu_race_df = pd.merge(edu_df.drop(columns=['Estimate_Total', 'B15003_025', 'Percent_Male', 'Percent_Female']), race_df.drop(columns=['Estimate_Total']), on=['County'])
c:\Users\19037\Documents\Measels_Vaccination\code_backup\vaccination_functions.py:107: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_acs_variables = pd.merge(pd.merge(edu_race_df, enroll_age_df, on=['County']), poverty_df, on=['

## PCA Code Development for vaccination_functions.py

In [12]:
n = 10
scaler = MinMaxScaler()
pca_model = PCA(n_components=n)
y_data = all_vac_set_no_gender_percent['MMR Vaccination Rate']
x_data = all_vac_set_no_gender_percent.drop(columns=['MMR Vaccination Rate', 'County'])
x_scaler = scaler.fit_transform(x_data)
x_pca = pca_model.fit_transform(x_scaler)
#modelR = Ridge(alpha=1.0).fit(x_pca, y_data)

In [72]:
coef_list= []
for i in range(10):
    x_boot, y_boot = resample(x_pca, y_data)
    modelR = Ridge(alpha=1.0).fit(x_boot, y_boot)
    coef_list.append(modelR.coef_)

In [73]:
component_names = ['PC'+str(x) for x in range(n)]
df = pd.DataFrame(coef_list,  columns=component_names)

In [74]:
ci_lower = np.percentile(df, 2.5, axis=0)
ci_upper = np.percentile(df, 97.5, axis=0)
coef_mean = np.mean(df, axis=0).to_numpy()

ci_results_df = pd.DataFrame({'Predictor': component_names,
                                            'Mean': coef_mean,
                                            'CI_Lower': ci_lower,
                                            'CI_Upper': ci_upper})
    
ci_results_df["Explained Variance"] = pca_model.explained_variance_ratio_
ci_results_df['Coeff Signficance'] = ['Not Signficant' if l <= 0 <= u else 'Signficant' for l,u in zip(ci_results_df['CI_Lower'], ci_results_df['CI_Upper'])]


In [75]:
ci_results_df

,Predictor,Mean,CI_Lower,CI_Upper,Explained Variance,Coeff Signficance
0,PC0,-0.963287,-1.566031,-0.592982,0.387142,Signficant
1,PC1,-4.315649,-5.077795,-3.242774,0.146853,Signficant
2,PC2,0.903437,0.096109,1.916642,0.094867,Signficant
3,PC3,0.594967,-0.213793,1.608221,0.052322,Not Signficant
4,PC4,-0.394892,-1.712504,0.706513,0.034868,Not Signficant
5,PC5,-3.932990,-4.557611,-2.801281,0.028590,Signficant
6,PC6,0.194885,-0.802084,1.469780,0.022606,Not Signficant
7,PC7,3.062553,1.525435,4.833905,0.018589,Signficant
8,PC8,1.789361,-0.639588,3.703858,0.015336,Not Signficant
9,PC9,-3.259760,-5.973463,-1.976963,0.012134,Signficant


In [77]:
x_pca

array([[-0.53196273, -0.0601421 ,  0.34766703, ..., -0.11764175,
        -0.04990058, -0.02983319],
       [-0.53196273, -0.0601421 ,  0.34766703, ..., -0.11764175,
        -0.04990058, -0.02983319],
       [-0.53196273, -0.0601421 ,  0.34766703, ..., -0.11764175,
        -0.04990058, -0.02983319],
       ...,
       [-0.29969   , -1.23464949, -0.60533858, ...,  0.35480156,
        -0.21762784, -0.00364104],
       [-0.29969   , -1.23464949, -0.60533858, ...,  0.35480156,
        -0.21762784, -0.00364104],
       [-0.29969   , -1.23464949, -0.60533858, ...,  0.35480156,
        -0.21762784, -0.00364104]], shape=(3082, 10))

In [79]:
pc_df = pd.DataFrame(x_pca, columns=component_names)
pc_df

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9
0,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
1,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
2,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
3,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
4,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
...,...,...,...,...,...,...,...,...,...,...
3077,-0.129009,-1.231920,-0.780149,-0.375005,-0.105225,0.106729,0.145727,0.392482,-0.008380,-0.160790
3078,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,-0.191885,-0.048245,0.354802,-0.217628,-0.003641
3079,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,-0.191885,-0.048245,0.354802,-0.217628,-0.003641
3080,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,-0.191885,-0.048245,0.354802,-0.217628,-0.003641


In [85]:
sig_predictors = ci_results_df[ci_results_df['Coeff Signficance'] == 'Signficant']['Predictor']
#ci_results_df[ci_results_df['Coeff Signficance'] == 'Signficant']['Predictor']

In [88]:
pc_df_sig = pc_df[sig_predictors]
pc_df_sig['MMR'] = y_data
pc_df_sig

,PC0,PC1,PC2,PC5,PC7,PC9,MMR
0,-0.531963,-0.060142,0.347667,-0.602543,-0.117642,-0.029833,90.24
1,-0.531963,-0.060142,0.347667,-0.602543,-0.117642,-0.029833,93.00
2,-0.531963,-0.060142,0.347667,-0.602543,-0.117642,-0.029833,96.23
3,-0.531963,-0.060142,0.347667,-0.602543,-0.117642,-0.029833,93.75
4,-0.531963,-0.060142,0.347667,-0.602543,-0.117642,-0.029833,96.28
...,...,...,...,...,...,...,...
3077,-0.129009,-1.231920,-0.780149,0.106729,0.392482,-0.160790,100.00
3078,-0.299690,-1.234649,-0.605339,-0.191885,0.354802,-0.003641,100.00
3079,-0.299690,-1.234649,-0.605339,-0.191885,0.354802,-0.003641,100.00
3080,-0.299690,-1.234649,-0.605339,-0.191885,0.354802,-0.003641,100.00


In [92]:
coef_list2 = []
for i in range(10):
    x_boot2, y_boot2 = resample(pc_df_sig.drop(columns='MMR'), pc_df_sig['MMR'])
    modelR_2 = Ridge(alpha=1.0).fit(x_boot2, y_boot2)
    coef_list2.append(modelR_2.coef_)

In [96]:
#coef_list2
coef_df2 = pd.DataFrame(coef_list2, columns=pc_df_sig.drop(columns='MMR').columns)
#coef_df2
ci_lower2 = np.percentile(coef_df2, 2.5, axis=0)
ci_upper2 = np.percentile(coef_df2, 97.5, axis=0)
coef_mean2 = np.mean(coef_df2, axis=0).to_numpy()

ci_results_df2 = pd.DataFrame({'Predictor': pc_df_sig.drop(columns='MMR').columns,
                                            'Mean': coef_mean2,
                                            'CI_Lower': ci_lower2,
                                            'CI_Upper': ci_upper2})
    
ci_results_df2['Coeff Signficance'] = ['Not Signficant' if l <= 0 <= u else 'Signficant' for l,u in zip(ci_results_df2['CI_Lower'], ci_results_df2['CI_Upper'])]

ci_results_df2

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,PC0,-0.823422,-1.336904,-0.254379,Signficant
1,PC1,-4.763591,-6.057674,-3.486590,Signficant
2,PC2,1.231788,0.611045,2.098301,Signficant
3,PC5,-3.195080,-4.405657,-2.103202,Signficant
4,PC7,3.145578,1.584391,4.876722,Signficant
5,PC9,-2.649997,-4.890700,-1.091059,Signficant


In [68]:
x_pca[:,0]

array([-0.53196273, -0.53196273, -0.53196273, ..., -0.29969   ,
       -0.29969   , -0.29969   ], shape=(3082,))

In [70]:
x_pca[:,:3]

array([[-0.53196273, -0.0601421 ,  0.34766703],
       [-0.53196273, -0.0601421 ,  0.34766703],
       [-0.53196273, -0.0601421 ,  0.34766703],
       ...,
       [-0.29969   , -1.23464949, -0.60533858],
       [-0.29969   , -1.23464949, -0.60533858],
       [-0.29969   , -1.23464949, -0.60533858]], shape=(3082, 3))

In [18]:
x_pca

array([[-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
       [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
       [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
       ...,
       [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
       [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
       [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464]],
      shape=(3082, 5))

In [52]:
num_components = x_pca.shape[1]

In [56]:
cols = ['PCA'+str(x) for x in range(num_components)]
cols

['PCA0', 'PCA1', 'PCA2', 'PCA3', 'PCA4']

In [29]:
[y_data.values, x_pca]

[array([ 90.24,  93.  ,  96.23, ..., 100.  , 100.  , 100.  ], shape=(3082,)),
 array([[-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
        [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
        [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
        ...,
        [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
        [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
        [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464]],
       shape=(3082, 5))]

In [37]:
coef_df = pd.DataFrame(x_pca,  columns=['PCA1', 'PCA2', 'PCA3', 'PCA4', 'PCA5'])

In [38]:
coef_df['Measels_Vac_Rate'] = y_data.values

In [39]:
coef_df

,PCA1,PCA2,PCA3,PCA4,PCA5,Measels_Vac_Rate
0,-0.531963,-0.060142,0.347667,0.275815,-0.242300,90.24
1,-0.531963,-0.060142,0.347667,0.275815,-0.242300,93.00
2,-0.531963,-0.060142,0.347667,0.275815,-0.242300,96.23
3,-0.531963,-0.060142,0.347667,0.275815,-0.242300,93.75
4,-0.531963,-0.060142,0.347667,0.275815,-0.242300,96.28
...,...,...,...,...,...,...
3077,-0.129009,-1.231920,-0.780149,-0.375005,-0.105225,100.00
3078,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,100.00
3079,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,100.00
3080,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,100.00


In [43]:
coef_list = []
for i in range(100):
    x_boot, y_boot = resample(x_pca, y_data)
    model = Ridge(alpha=1.0).fit(x_boot, y_boot)

    coef_list.append(model.coef_)

In [44]:
coef_list

[array([-0.58368312, -3.86847023,  0.4158315 , -0.51401088,  0.35238539]),
 array([-1.03458772, -4.4188667 ,  0.69695081, -0.85371833, -0.6507871 ]),
 array([-1.16973629, -3.69049483,  3.10514929,  0.44331896, -0.39009034]),
 array([-1.04484519, -4.58190042,  0.79644704,  0.59800928, -0.72919818]),
 array([-0.79971969, -4.82903469,  1.36092854,  1.07714456,  1.12889121]),
 array([-1.04167992, -4.3829248 ,  2.0409906 , -0.03890884, -0.52266628]),
 array([-0.3766142 , -4.76449358,  0.97149669, -0.17781623, -0.09126731]),
 array([-0.00646861, -4.37731753,  1.01544892,  0.66519749,  1.09090201]),
 array([-0.74050573, -4.80891014,  2.08386223, -0.40397605,  0.4353146 ]),
 array([-1.38877239, -5.40775072,  0.52106451,  1.43850701, -1.81776062]),
 array([-1.25898263, -4.11505185,  1.58622827,  0.06658805, -0.94076593]),
 array([-0.94629873, -5.32576001,  1.38560534,  1.18419913,  0.63398907]),
 array([-0.52388188, -3.93496299,  1.13862769,  0.58482055,  0.40759769]),
 array([-0.81523679, -4.6

In [46]:
coef_df_2 = pd.DataFrame(coef_list, columns=coef_df.drop(columns="Measels_Vac_Rate").columns)

In [47]:
coef_df_2

,PCA1,PCA2,PCA3,PCA4,PCA5
0,-0.583683,-3.868470,0.415832,-0.514011,0.352385
1,-1.034588,-4.418867,0.696951,-0.853718,-0.650787
2,-1.169736,-3.690495,3.105149,0.443319,-0.390090
3,-1.044845,-4.581900,0.796447,0.598009,-0.729198
4,-0.799720,-4.829035,1.360929,1.077145,1.128891
...,...,...,...,...,...
95,-0.856782,-4.272916,1.365585,-0.409955,-1.669829
96,-0.840720,-3.900299,2.461650,2.220469,0.446488
97,-0.757302,-4.520856,2.054356,1.009962,0.517251
98,-1.219320,-4.940810,0.214307,0.442335,-2.791174


In [48]:
### calculate lower CI (2.5%), upper CI (97.5%) and mean of each predictor coefficient
ci_lower = np.percentile(coef_df_2, 2.5, axis=0)
ci_upper = np.percentile(coef_df_2, 97.5, axis=0)
coef_mean = np.mean(coef_df_2, axis=0).to_numpy()

ci_results_df = pd.DataFrame({'Predictor': coef_df.drop(columns="Measels_Vac_Rate").columns,
                                            'Mean': coef_mean,
                                            'CI_Lower': ci_lower,
                                            'CI_Upper': ci_upper})

In [49]:
ci_results_df

,Predictor,Mean,CI_Lower,CI_Upper
0,PCA1,-0.874482,-1.446161,-0.342855
1,PCA2,-4.568743,-5.512594,-3.691972
2,PCA3,1.176979,0.099615,2.185013
3,PCA4,0.250619,-0.839290,1.502251
4,PCA5,-0.217064,-1.936490,1.420068


In [31]:
pca_model.explained_variance_ratio_

array([0.38714207, 0.14685255, 0.094867  , 0.05232196, 0.03486847])

## Running for real results for PCA

In [ ]:
all_ridge_percent_df5, ridge_pca5_r2, ridge_pca5_sig, y_ridge_pca5_results = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Ridge", num_components=5)
#all_ridge_percent_df5

,Predictor,Mean,CI_Lower,CI_Upper,Explained Variance,Coeff Signficance
0,PC0,-0.874527,-1.447400,-0.314860,0.387142,Signficant
1,PC1,-4.536356,-5.519229,-3.565818,0.146853,Signficant
2,PC2,1.140400,-0.017415,2.251881,0.094867,Not Signficant
3,PC3,0.205182,-1.146569,1.663377,0.052322,Not Signficant
4,PC4,-0.144410,-2.027250,1.597074,0.034868,Not Signficant


In [13]:
ridge_pca5_r2

0.03444542661698835

In [ ]:
all_linear_percent_df5, linear_pca5_r2, linear_pca5_sig, y_linear_pca5_results = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Linear", num_components=5)
#all_linear_percent_df5

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,PCA0,-0.892752,-1.472313,-0.311534,Signficant
1,PCA1,-4.525461,-5.481831,-3.510365,Signficant
2,PCA2,1.154316,0.076503,2.237823,Signficant
3,PCA3,0.189697,-1.299022,1.702437,Not Signficant
4,PCA4,-0.144057,-2.037549,1.606355,Not Signficant


In [12]:
#number_components_array = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
#number_components_array = np.arange(2, 10+1)
number_components_array = np.arange(2, 35+1)

In [13]:
linear_results_dict = {}
ridge_results_dict = {}
results_r2_list = []
for n in number_components_array:
    all_linear_percent_df, linear_pca_r2, linear_pca_sig_r2, y_results_linear_pca = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Linear", num_components=n)
    linear_results_r2_list = []
    linear_results_r2_list.append(all_linear_percent_df)
    linear_results_r2_list.append(linear_pca_r2)
    linear_results_r2_list.append(linear_pca_sig_r2)
    linear_results_r2_list.append(y_results_linear_pca)
    linear_results_dict[f"{n}"] = linear_results_r2_list

    all_ridge_percent_df, ridge_pca_r2, ridge_pca_sig_r2, y_results_ridge_pca = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Ridge", num_components=n)
    ridge_results_r2_list = []
    ridge_results_r2_list.append(all_ridge_percent_df)
    ridge_results_r2_list.append(ridge_pca_r2)
    ridge_results_r2_list.append(ridge_pca_sig_r2)
    ridge_results_r2_list.append(y_results_ridge_pca)
    ridge_results_dict[f"{n}"] = ridge_results_r2_list

In [20]:
linear_results_dict['2'][1]

0.03444557563194306

In [ ]:
linear_results_dict['4'][0][linear_results_dict['4'][0]['Coeff Signficance'] == 'Signficant']

,Predictor,Mean,CI_Lower,CI_Upper,Explained Variance,Coeff Signficance
0,PCA0,-0.883090,-1.453483,-0.318500,0.387142,Signficant
1,PCA1,-4.537578,-5.536254,-3.524958,0.146853,Signficant
2,PCA2,1.177385,0.134808,2.321960,0.094867,Signficant


In [15]:
for key in linear_results_dict.keys():
    cum_ev = linear_results_dict[key][0]['Explained Variance'].sum()
    sig_df = linear_results_dict[key][0][linear_results_dict[key][0]['Coeff Signficance'] == 'Signficant']
    cum_sig_ev = sig_df['Explained Variance'].sum()
    num_rows = len(sig_df.index)
    r2 = linear_results_dict[key][1]
    r2_sig = linear_results_dict[key][2]

    print(f"{key}: Total Expl = {cum_ev:.2f}, # of Sig PCs = {num_rows}, Sig Exp = {cum_sig_ev:.2f}, R2_OG = {r2:.3f}, R2_sig = {r2_sig:.3f}")

2: Total Expl = 0.53, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.036, R2_sig = 0.036
3: Total Expl = 0.63, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.032, R2_sig = 0.032
4: Total Expl = 0.68, # of Sig PCs = 3, Sig Exp = 0.63, R2_OG = 0.028, R2_sig = 0.029
5: Total Expl = 0.72, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.024, R2_sig = 0.023
6: Total Expl = 0.74, # of Sig PCs = 4, Sig Exp = 0.66, R2_OG = 0.032, R2_sig = 0.033
7: Total Expl = 0.77, # of Sig PCs = 4, Sig Exp = 0.66, R2_OG = 0.036, R2_sig = 0.038
8: Total Expl = 0.79, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.036, R2_sig = 0.041
9: Total Expl = 0.80, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.029, R2_sig = 0.029
10: Total Expl = 0.81, # of Sig PCs = 5, Sig Exp = 0.59, R2_OG = 0.040, R2_sig = 0.035


In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Linear", sig_feats=True)

In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Linear")

In [ ]:
#linear_results_dict['25'][0].to_csv(f"../linear_regression_fit_results/pca25_linear_regression_fit.csv")
#linear_results_dict['35'][0].to_csv(f"../linear_regression_fit_results/pca35_linear_regression_fit.csv")

In [16]:
for key in ridge_results_dict.keys():
    cum_ev = ridge_results_dict[key][0]['Explained Variance'].sum()
    sig_df = ridge_results_dict[key][0][ridge_results_dict[key][0]['Coeff Signficance'] == 'Signficant']
    cum_sig_ev = sig_df['Explained Variance'].sum()
    num_rows = len(sig_df.index)
    r2 = ridge_results_dict[key][1]
    r2_sig = ridge_results_dict[key][2]

    print(f"{key}: Total Expl = {cum_ev:.2f}, # of Sig PCs = {num_rows}, Sig Exp = {cum_sig_ev:.2f}, R2_OG = {r2:.3f}, R2_sig = {r2_sig:.3f} ")

2: Total Expl = 0.53, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.023, R2_sig = 0.023 
3: Total Expl = 0.63, # of Sig PCs = 3, Sig Exp = 0.63, R2_OG = 0.044, R2_sig = 0.044 
4: Total Expl = 0.68, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.033, R2_sig = 0.034 
5: Total Expl = 0.72, # of Sig PCs = 3, Sig Exp = 0.63, R2_OG = 0.049, R2_sig = 0.052 
6: Total Expl = 0.74, # of Sig PCs = 3, Sig Exp = 0.56, R2_OG = 0.041, R2_sig = 0.041 
7: Total Expl = 0.77, # of Sig PCs = 3, Sig Exp = 0.56, R2_OG = 0.064, R2_sig = 0.065 
8: Total Expl = 0.79, # of Sig PCs = 5, Sig Exp = 0.68, R2_OG = 0.029, R2_sig = 0.031 
9: Total Expl = 0.80, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.063, R2_sig = 0.060 
10: Total Expl = 0.81, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.054, R2_sig = 0.051 


In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Ridge", sig_feats=True)

In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Ridge")

In [ ]:
#ridge_results_dict['25'][0].to_csv(f"../ridge_regression_fit_results/pca25_ridge_regression_fit.csv")
#ridge_results_dict['34'][0].to_csv(f"../ridge_regression_fit_results/pca34_ridge_regression_fit.csv")